routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PersonController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [PersonController::class, 'index']);
Route::get('/tree', [PersonController::class, 'tree']);
Route::get('/add', [PersonController::class, 'add']);
Route::get('/edit/{id}', [PersonController::class, 'edit']);
Route::post('/create', [PersonController::class, 'create']);
Route::put('/update', [PersonController::class, 'update']);
Route::delete('/delete/{id}', [PersonController::class, 'destroy']);

app/Models/Person.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Casts\Attribute;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Person extends Model
{
    use HasFactory;
    protected $table = 'persons';
    
    protected $fillable = [
        'parent_id', 'name', 'gender'
    ];
    
    protected function getParentNameAttribute($value)
    {
        return self::select('name')->where('id', $this->parent_id)->first()->name ?? '-';
    }
    
    protected function getGenderAttribute($value)
    {
        return $value == 'm' ? 'Male' : 'Female';
    }

    protected function getCreatedAtAttribute($value)
    {
        return date('d, M Y', strtotime($value));
    }

    protected function getUpdatedAtAttribute($value)
    {
        return date('d, M Y', strtotime($value));
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Api/PersonController.php
<?php

namespace App\Http\Controllers\Api;

use App\Facades\Helper;
use Illuminate\Http\Request;
use App\Factory\ResponseFactory;
use App\Http\Controllers\Controller;
use App\Repository\Person\PersonRepository;

class PersonController extends Controller
{
    protected $person;    

    public function __construct(PersonRepository $person)
    {
        $this->person = $person;
    }

    public function all()
    {
        $data = $this->person->getAllData();
        return ResponseFactory::success($data, "Success Get All Data");
    }

    public function find($id)
    {
        $data = $this->person->findData($id);
        return ResponseFactory::success($data, "Success Get Data");
    }
    
    public function create(Request $request)
    {
        $store = $request->only('name', 'parent_id', 'gender');
        $data = $this->person->updateOrCreate($store);
        return ResponseFactory::condition($data, "Create Data Persons", 201);
    }
    
    public function update(Request $request)
    {
        $store = $request->only('id', 'name', 'parent_id', 'gender');
        $data = $this->person->updateOrCreate($store);
        return ResponseFactory::condition($data, "Create Update Persons", 200);
    }

    public function destroy($id)
    {
        $isDeleted = $this->person->destroy($id);
        return ResponseFactory::success($id, "Success Delete Data");
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/PersonController.php
<?php

namespace App\Http\Controllers;

use App\Facades\Helper;
use Illuminate\Http\Request;
use App\Http\Requests\StorePersonRequest;
use App\Repository\Person\PersonRepository;

class PersonController extends Controller
{
    protected $person;    

    public function __construct(PersonRepository $person)
    {
        $this->person = $person;
    }

    public function index()
    {
        $data = $this->person->getAllData();
        return view('index', ['data' => $data]);
    }

    public function add()
    {
        $data['parent'] = $this->person->getParentData();
        return view('form', $data);
    }

    public function edit($id)
    {
        $data['parent'] = $this->person->getParentData($id);
        $data['person'] = $this->person->findData($id);
        return view('form', $data);
    }
    
    public function create(StorePersonRequest $request)
    {
        $store = $request->only('name', 'parent_id', 'gender');
        $data = $this->person->updateOrCreate($store);
        return Helper::condReturnRedirectBack($data, "Insert Data");
    }

    public function tree()
    {
        $data['persons'] = $this->person->getTreeData();
        return view('tree', $data);
    }
    
    public function update(StorePersonRequest $request)
    {
        $store = $request->only('id', 'name', 'parent_id', 'gender');
        $data = $this->person->updateOrCreate($store);
        return Helper::condReturnRedirectBack($data, "Update Data");
    }

    public function destroy($id)
    {
        $isDeleted = $this->person->destroy($id);
        return Helper::condReturnRedirectBack($isDeleted, "Delete Data");
    }
}

resources/views/form.blade.php
@extends('layouts.app')

@section('title', isset($person) ? 'Edit' : 'Add')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ isset($person) ? 'Edit Person' : 'Create Person' }}</div>

                    <div class="card-body">
                        <a href="/">Back to Home</a>
                        <form id="itemFrom" role="form" method="POST"
                            action="{{ isset($person) ? '/update/' : '/create' }}">
                            @csrf
                            @isset($person)
                                @method('PUT')
                            @endisset

                            <div class="card-body">

                                @isset($person)
                                    <input type="hidden" name="id" value="{{ $person->id }}">
                                @endisset
                                <div class="form-group">
                                    <label>Name</label>
                                    <input type="text" name="name" value="{{ $person->name ?? '' }}" required>
                                </div>

                                <div class="form-group">
                                    <label>Gender</label>
                                    <select name="gender" required>
                                        <option value="m"
                                            {{ isset($person->gender) && $person->gender == 'Male' ? 'selected' : '' }}>
                                            Male
                                        </option>
                                        <option value="f"
                                            {{ isset($person->gender) && $person->gender == 'Female' ? 'selected' : '' }}>
                                            Female
                                        </option>
                                    </select>
                                </div>

                                <div class="form-group">
                                    <label>Parent</label>
                                    <select name="parent_id" required>
                                        @foreach ($parent as $item)
                                            <option value="{{ $item->id }}"
                                                {{ isset($person->parent_id) && $person->parent_id == $item->id ? 'selected' : '' }}>
                                                {{ $item->name }}</option>
                                        @endforeach
                                    </select>
                                </div>

                                <button type="submit" class="btn btn-primary">
                                    @isset($person)
                                        <i class="fas fa-arrow-circle-up"></i>
                                        <span>Update</span>
                                    @else
                                        <i class="fas fa-plus-circle"></i>
                                        <span>Create</span>
                                    @endisset
                                </button>

                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/index.blade.php
@extends('layouts.app')

@section('title', 'Index')

@section('content')
    <a href="/tree">Tree Family</a>
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Index</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-success" href="/add" title="Create a new person"> <i class="fas fa-plus-circle"></i>
                    </a>
            </div>
        </div>
    </div>

    <table class="table table-bordered table-responsive-lg">
        <tr>
            <th>Name</th>
            <th>Parent</th>
            <th>Gender</th>
            <th>Date Created</th>
            <th>Date Updated</th>
            <th>Actions</th>
        </tr>
        @foreach ($data as $item)
            <tr>
                <td>{{ $item->name }}</td>
                <td>{{ $item->parent_name }}</td>
                <td>{{ $item->gender }}</td>
                <td>{{ $item->created_at }}</td>
                <td>{{ $item->updated_at }}</td>
                <td>
                    <form action="/delete/{{ $item->id }}" method="POST">
                        <a href="/edit/{{ $item->id }}">
                            <i class="fas fa-edit fa-lg"></i>
                        </a>

                        @csrf

                        @method('DELETE')

                        <button type="submit" title="delete" style="border: none; background-color:transparent;">
                            <i class="fas fa-trash fa-lg text-danger"></i>
                        </button>
                    </form>
                </td>
            </tr>
        @endforeach
    </table>

@endsection

resources/views/layouts/app.blade.php
<html>

<head>
    <title>Tree Family - @yield('title')</title>

    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/css/bootstrap.css" rel="stylesheet">
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js"
        integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous">
    </script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js"
        integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous">
    </script>

    <style>
        .footer {
            position: fixed;
            left: 0;
            bottom: 0;
            width: 100%;
            background-color: #9C27B0;
            color: white;
            text-align: center;
        }
    </style>

    @stack('styles')

</head>

<body>
    <div class="container" style="margin-top: 40px;">
        @include('utils.message')
        @yield('content')
    </div>
</body>

</html>

resources/views/tree.blade.php
@extends('layouts.app')

@push('styles')
    <link href="{{ asset('css/tree.css') }}" rel="stylesheet">
@endpush
@section('content')
    <section class="treeMainContainer">
        <div class="treeContainer d_f">
            <div class="_NewBranch d_f">
                @foreach ($persons as $key => $item)
                    @if (!$item->is_has_parent)
                        <div class="_treeRoot d_f">
                            <div class="_treeBranch hasChildren">
                                <div class="_treeRaw d_f">
                                    <div class="_treeLeaf d_f">
                                        <div class="t_Data d_f">
                                            <p class="shortName"> {{ $item->name }} </p>
                                        </div>
                                    </div>
                                </div>
                                @php unset($persons[$key]);@endphp
                                {!! \App\Facades\Helper::drawTreeBranch($persons, $item->id) !!}
                            </div>
                        </div>
                    @endif
                @endforeach
            </div>
        </div>
    </section>
@endsection

resources/views/utils/message.blade.php
@if ($message = Session::get('success'))
    <div class="alert alert-success">
        <p>{{ $message }}</p>
    </div>
@endif
@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif